export const FETCH_WOMENS_CLOTHING = "FETCH_WOMENS_CLOTHING";
export const FETCH_WOMENS_CLOTHING_SUCCESS = "FETCH_WOMENS_CLOTHING_SUCCESS";
export const FETCH_WOMENS_CLOTHING_ERROR = "FETCH_WOMENS_CLOTHING_ERROR";
export const CHANGE_SORT = "CHANGE_SORT";

export const CLEAN_QUERY = "CLEAN_QUERY";
export const START_SEARCH = "START_SEARCH";
export const FINISH_SEARCH = "FINISH_SEARCH";
export const UPDATE_SELECTION = "UPDATE_SELECTION";
